<?php
/**
 * Created by PhpStorm.
 * User: E.FARID
 * Date: 28-Sep-19
 * Time: 3:35 AM
 */
namespace App\Table;
use Cake\ORM\Table;

class RolesTable extends Table {
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        //Behaviour
        $this->addBehavior('Timestamp');

        //Associations
        $this->hasMany('Users',[
            'className' => 'Users',
            'foreignKey' => 'role_id'
        ]);
    }
}